stages:
  - deploy

deploy-job:
  stage: deploy
  script:
    - if [ "$CI_COMMIT_TAG" = "" ] ; then echo "Need add tag!";
      else 
        ssh -o StrictHostKeyChecking=no ubuntu@app.kashin.store sudo chown ubuntu /var/www/kashin.store -R;
        scp -q -o StrictHostKeyChecking=no -r $CI_PROJECT_DIR/wp/* ubuntu@app.kashin.store:/var/www/kashin.store/;
        ssh -o StrictHostKeyChecking=no ubuntu@app.kashin.store sudo chown www-data /var/www/kashin.store -R;
      fi
    - echo "Finish"
